version: 0.2

phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - docker build -t fargate-demo-docker:latest .
      - docker tag fargate-demo-docker:latest 398287015812.dkr.ecr.us-east-1.amazonaws.com/fargate-demo-docker-repo:latest
  post_build:
    commands:
      - docker push 398287015812.dkr.ecr.us-east-1.amazonaws.com/fargate-demo-docker-repo:latest
      - printf '[{"name":"at-ecs-task","imageUri":"398287015812.dkr.ecr.us-east-1.amazonaws.com/fargate-demo-docker-repo"}]' 398287015812.dkr.ecr.us-east-1.amazonaws.com/fargate-demo-docker-repo:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
